# ========================================
# PIPELINES CONFIGURATION
# ========================================

- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline/*.conf"
  pipeline.workers: 2
  pipeline.batch.size: 125